# Generated by Django 4.1.1 on 2023-04-04 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_patient_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_data',
            name='nodal_skin',
        ),
    ]
