# Generated by Django 4.1.1 on 2023-04-04 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_remove_patient_data_nodal_skin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_data',
            name='continous_sneezing',
        ),
    ]
