# Generated by Django 4.1.1 on 2023-04-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_remove_patient_data_continous_sneezing'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='bio',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
