# Generated by Django 4.1.1 on 2023-04-15 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_appuser_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='bio',
            new_name='history',
        ),
    ]
