# Generated by Django 4.1.4 on 2023-04-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_rename_bio_appuser_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='history',
            field=models.CharField(default='NA', max_length=200),
        ),
    ]
