# Generated by Django 4.1.1 on 2023-04-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_rename_bio_appuser_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='history',
        ),
        migrations.AddField(
            model_name='appuser',
            name='age',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='appuser',
            name='sex',
            field=models.CharField(default='NA', max_length=20),
        ),
    ]
