# Generated by Django 4.1.1 on 2023-04-20 17:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_remove_appuser_history_appuser_age_appuser_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='medical_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='sex',
            field=models.CharField(default='Not to say', max_length=20),
        ),
    ]
